### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by ericafenyo** [ericafenyo/bike-diary#35]
**Child issues:**

- [x] Add a login ui  #30 
- [x] Add a sign up ui #31
- [x] Add input validation to login and signup ui #34
- [x] Create user account #36
- [x] Forgot password #37
- [x] Login to user account #39
- [x] Verify email address #38
