### ISSUE TITLE
Track users cycling path

### ISSUE THREAD

**Issue by ericafenyo** [ericafenyo/bike-diary#7]
We need to track the users cycling path in realtime to display it on a map interface.

In general, we need to create a finite state machine to keep track of various transitions. From a start state to a  pause for example. This is a little completed so we treat this issue as an epic with sub-issues.

BLOCKED BY:
- [x] [Add location updates](https://github.com/ericafenyo/bike-diary/issues/2 ). (https://developer.android.com/training/location/request-updates)
- [x] [Add a notification implementation](https://github.com/ericafenyo/bike-diary/issues/3 )
- [x] [Implement logging](https://github.com/ericafenyo/bike-diary/issues/4)
- [x] [ Save location updates to database](https://github.com/ericafenyo/bike-diary/issues/5 )
- [x] [Create a FSM ( Finite State Machine ) handling bike transition states](https://github.com/ericafenyo/bike-diary/issues/6)
- [x] [( Finite State Machine ) Handle "tracker initialize" action](https://github.com/ericafenyo/bike-diary/issues/8)
- [x] [( Finite State Machine ) Handle "tracker start" action](https://github.com/ericafenyo/bike-diary/issues/9)
- [x] [( Finite State Machine ) Handle "tracker pause" action](https://github.com/ericafenyo/bike-diary/issues/10)
- [x] [( Finite State Machine ) Handle "tracker resume" action](https://github.com/ericafenyo/bike-diary/issues/11)
- [x] [( Finite State Machine ) Handle "tracker stop" action](https://github.com/ericafenyo/bike-diary/issues/12)
